services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_ENV: local-docker
      APP_VERSION: 1.0.0
    init: true
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
